# Generated by Django 5.2.6 on 2025-10-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайли'},
        ),
        migrations.AddField(
            model_name='profile',
            name='email_consent',
            field=models.BooleanField(default=True, verbose_name='Згода на розсилку email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Чоловік'), ('female', 'Жінка')], max_length=10, verbose_name='sex'),
        ),
    ]
