# Generated by Django 5.2.7 on 2025-10-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_profile_email_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_consent',
            field=models.BooleanField(default=True, verbose_name='agree on get an email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'man'), ('female', 'women')], max_length=10, verbose_name='sex'),
        ),
    ]
