# Generated by Django 5.2.7 on 2025-10-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_account_type_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('full', 'full mode'), ('free', 'free mode')], default='free', max_length=30),
        ),
    ]
