# Generated by Django 5.2.7 on 2025-10-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.png', upload_to='courses_images', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Unique name of lesson')),
                ('title', models.CharField(max_length=100, verbose_name='Name of lesson')),
                ('desc', models.TextField(verbose_name='Description of lesson')),
                ('number', models.IntegerField(verbose_name='Lesson number')),
                ('video', models.CharField(max_length=100, verbose_name='Video')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='which course?')),
            ],
        ),
    ]
